### ISSUE TITLE
Make subject customisable?

### ISSUE THREAD

**Issue by toshotosho** [timnashcouk/wp_user_sentry#1]
Could you make the subject to support the same set of placeholders as the body of the email?

I see there is a filter that potentially can do this, but the raw data about the login is not passed to it, so I can't put "You just logged in from Italy!" in the subject unless I have it in the email body and then parse it to get the info.

**Comment by timnashcouk** [comment]
That seems an entirely reasonable request, I made the body modifiable and completely forgot the subject line!
